### ISSUE TITLE
'NoneType' Error

### ISSUE THREAD

**Issue by J9rryGou** [terrierteam/pyterrier_pisa#12]
![image](https://user-images.githubusercontent.com/106114570/196289857-2757f09c-dd84-44c3-8e37-0d27fe324dbd.png)

Can someone help this? I am following the tutorial at 
https://github.com/cmacdonald/pyterrier-msmarco-document-leaderboard-runs/blob/master/uogTrBaseDPH.ipynb

**Comment by cmacdonald** [comment]
Works fine for me. 

```
>>> import pyterrier as pt
>>> pt.init()
PyTerrier 0.8.1 has loaded Terrier 5.6 (built by craigmacdonald on 2021-09-17 13:27)

No etc/terrier.properties, using terrier.default.properties for bootstrap configuration.
>>> dataset = pt.get_dataset("msmarco_document")
>>> dataset.get_corpus()
Downloading msmarco_document corpus to /home/me/.pyterrier/corpora/msmarco_document/corpus
msmarco-docs.trec.gz:   0%|                                                         | 1.09M/7.92G [00:01<4:34:09, 517kiB/s]
```

I also checked, if the datasets is wrongly spelt, you get an error
```
>>> dataset = pt.get_dataset("msmarco-document")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/pyterrier/datasets.py", line 1080, in get_dataset
    rtr = DATASET_MAP[name]
KeyError: 'msmarco-document'
```

Also, surely this issue is for [pyterrier](http://github.com/terrier-org/pyterrier) rather than pyt_pisa? ;-)

BTW, some prebuilt indices available from 
http://data.terrier.org/msmarco_document.dataset.html

**Comment by J9rryGou** [comment]
> Works fine for me.
> 
> ```
> >>> import pyterrier as pt
> >>> pt.init()
> PyTerrier 0.8.1 has loaded Terrier 5.6 (built by craigmacdonald on 2021-09-17 13:27)
> 
> No etc/terrier.properties, using terrier.default.properties for bootstrap configuration.
> >>> dataset = pt.get_dataset("msmarco_document")
> >>> dataset.get_corpus()
> Downloading msmarco_document corpus to /home/me/.pyterrier/corpora/msmarco_document/corpus
> msmarco-docs.trec.gz:   0%|                                                         | 1.09M/7.92G [00:01<4:34:09, 517kiB/s]
> ```
> 
> I also checked, if the datasets is wrongly spelt, you get an error
> 
> ```
> >>> dataset = pt.get_dataset("msmarco-document")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/opt/conda/lib/python3.7/site-packages/pyterrier/datasets.py", line 1080, in get_dataset
>     rtr = DATASET_MAP[name]
> KeyError: 'msmarco-document'
> ```
> 
> Also, surely this issue is for [pyterrier](https://github.com/terrier-org/pyterrier) rather than pyt_pisa? ;-)
> 
> BTW, some prebuilt indices available from http://data.terrier.org/msmarco_document.dataset.html

Yes, I want to use the pyterrier_pisa library to load the index created by PISA engine. When you want to shoot a query into PISA, you need to provide:
Take CW09B as an example:
term lexicon: CW09B.fwd.termlex
document lexicon: CW09B.url.fwd.doclex
WAND data: CW09B.wand
compressed inverted index: CW09B.index.opt
compress method: block_simdbp

You know, CW09B is quite large. It is not reasonable to create the index in realtime. Can we use the library to read these stuff and play something with index? The function I want to use your library is also very basic:

For a given term t and document d, I want to get the score of t in d. Is it possible to do this? Basically, I want to do the index loading one time and do such lookup in realtime.

Thanks!

So, I was just testing the function of this library so that I can make it load the index successfully.

**Comment by seanmacavaney** [comment]
> You know, CW09B is quite large. It is not reasonable to create the index in realtime. Can we use the library to read these stuff and play something with index?

Have you tried the suggestion from [this thread](https://github.com/terrier-org/pyterrier/issues/331)?

> For a given term t and document d, I want to get the score of t in d. Is it possible to do this? Basically, I want to do the index loading one time and do such lookup in realtime.

What do you mean by "score" for the term? Just the Term Frequency (TF)?

This functionality isn't built into PISA or pyterrier_pisa. PISA has a suggestion here, which you might be able to adapt to your needs: https://github.com/pisa-engine/pisa/blob/master/docs/source/inverting.md#reading-the-inverted-index-using-python

Hope this helps. If you get it working, it might be a nice feature to add to this package.

**Comment by cmacdonald** [comment]
>Yes, I want to use the pyterrier_pisa library to load the index created by PISA engine. When you want to shoot a query into PISA, you need to provide...

So I fail to see how this has anything to do with the reported error message. Its a different collection (MSMARCO vs CW90B), its Pisa vs Pyterrier core. You also dont tell us if you managed to resolve the original error message.

PLEASE one issue, one problem, and tell us if you resolved it.

**Comment by J9rryGou** [comment]
> > Yes, I want to use the pyterrier_pisa library to load the index created by PISA engine. When you want to shoot a query into PISA, you need to provide...
> 
> So I fail to see how this has anything to do with the reported error message. Its a different collection (MSMARCO vs CW90B), its Pisa vs Pyterrier core. You also dont tell us if you managed to resolve the original error message.
> 
> PLEASE one issue, one problem, and tell us if you resolved it.

Hi, 

I just want to test the function of the library so that I can use it to load the index of other collections. Unfortunately, I still get the same NoneType error while calling _get_corpus()_. Maybe because I did not set up the environment correctly?

That's OK for me now, because I found the link sent by Sean is very helpful. I can follow the step of that link at present. Will let you know if I have some problems after I use the library later.

Thanks!

Best,
Jerry

**Comment by seanmacavaney** [comment]
Marking this issue closed for now
