### ISSUE TITLE
Colab pip install fails

### ISSUE THREAD

**Issue by okhat** [terrierteam/pyterrier_pisa#18]
Very glad to see this repo! In the Colab, I get this error immediately on the first cell.

```
!pip install -q pyterrier-pisa
``

ERROR: Could not find a version that satisfies the requirement pyterrier-pisa (from versions: none)
ERROR: No matching distribution found for pyterrier-pisa

**Comment by seanmacavaney** [comment]
Thanks for reporting! Looks like it's because the Colab image has updated to Python 3.10, and there's no pre-built bdist for that on pypi. I'm working on getting one up.

**Comment by seanmacavaney** [comment]
It should work now! Can you give it a try?

**Comment by okhat** [comment]
Thanks a ton @seanmacavaney !

**Comment by okhat** [comment]
Btw you may consider updating the readme that you now support 3.9, 3.10
