### ISSUE TITLE
What is pyt_splade?

### ISSUE THREAD

**Issue by okhat** [terrierteam/pyterrier_pisa#19]
Where can we install that from?

**Comment by cmacdonald** [comment]
<https://github.com/cmacdonald/pyt_splade>
[pyt_splade.png]
cmacdonald/pyt_splade<https://github.com/cmacdonald/pyt_splade>
github.com<https://github.com/cmacdonald/pyt_splade>


Craig

Sent from my iPhone

On 22 Jun 2023, at 20:00, Omar Khattab ***@***.***> wrote:

﻿

Where can we install that from?

**Comment by okhat** [comment]
Thanks Craig! Hope you're well!

**Comment by seanmacavaney** [comment]
If you're keen on learned sparse stuff, there's also an integration with the pretty extensive [`lsr` package](https://github.com/thongnt99/learned-sparse-retrieval) here: https://github.com/thongnt99/learned-sparse-retrieval/blob/main/lsr/transformer.py
