### ISSUE TITLE
CIFF Support

### ISSUE THREAD

**Issue by seanmacavaney** [terrierteam/pyterrier_pisa#2]
As suggested by @amallia and @JMMackenzie

The Python interface could look something like:

```python
# import
PisaIndex.from_ciff('path/to/ciff')
# export
index.to_ciff('path/to/ciff')
```

Looks like there's relatively straightforward `ciff_to_pisa(in_path, out_path)` and `pisa_to_ciff(collection_path, terms_path, titles_path, out_path, description)` (what is titles_path?) functions provided in [this repository](https://github.com/pisa-engine/ciff). However, they are written in Rust -- not totally sure how easy it is to include a Python<->Rust interface.

**Comment by JMMackenzie** [comment]
Hey @seanmacavaney, this should help: https://pypi.org/project/pyciff

It's a python wrapper on the rust ciff tools which Michal wrote a while back. Take a look. The repo was private before (I think we forgot to open it up) if you want to check out the source: https://github.com/pisa-engine/pyciff

**Comment by elshize** [comment]
@seanmacavaney the the `terms_path` and `titles_path` would be the text files containing list of terms and "titles" (unique string IDs, like `DOCNO`), respectively. The titles file is a product of parsing a collection to a forward index, so this is something that should be available for anyone who did the whole parse/index pipeline using PISA. The reason why it doesn't have to be passed the other way around is that for simplicity's sake we just create it from the `out_path` and add an appropriate suffix (like all other files).

Certain files (and their names/paths) are not tied to the index itself as they aren't needed for all that you can do with the index. Gives us more flexibility, but makes it a bit more complex.

We do have some docs here: https://pisa.readthedocs.io/en/latest/getting_started.html though I'm not sure if they are 100% up to date. Maybe we should give it a look sometime soon.

Anyway, feel free to ask questions if anything is not clear.

**Comment by JMMackenzie** [comment]
I've just updated the docs at https://github.com/pisa-engine/pyciff so hopefully they are more clear (as Michal discussed above).

**Comment by seanmacavaney** [comment]
Excellent -- this package will certainly make adding this functionality to pyterrier_pisa easier. Thanks for clarifying that the `titles_path` should point to the `fwd.documents` file.

**Comment by seanmacavaney** [comment]
WIP on this branch: https://github.com/terrierteam/pyterrier_pisa/tree/ciff

This is pretty close, but it looks like it the ciff integration doesn't generate the `.termlex` file, which is needed to evaluate queries. I opened an issue [here](https://github.com/pisa-engine/ciff/issues/29). I poked around a bit, but I'm not very comfortable with either rust or the format of the `termlex` file itself.

If there's an alternate way to generate termlex (e.g., from a `.terms` file via the c api), I'm open to that too, of course.

----

Another slight complication is that it doesn't appear that ciff provides an indication about what type of stemming (or other pre-processing) was used to generate the index, so it will be up to the user to either specify the correct stemmer when they call `.from_ciff()` or perform the same stemming earlier in the pipeline. There doesn't seem to be a good way around this. I'll probably emit a warming to this effect when calling `.from_ciff()`, since it has the real potential to trip people up.

**Comment by elshize** [comment]
Yes, you're right about the term lexicon. There's an easy way to do it from command line with this: https://github.com/pisa-engine/pisa/blob/master/tools/lexicon.cpp, and if you look at the file, you also will see how to use `Payload_Vector` class.

Also, if you need more details: https://github.com/pisa-engine/pisa/blob/master/include/pisa/payload_vector.hpp

The general idea and format are simple: you are storing a bunch of objects, say, strings, which are preceded with a list of offsets. The positions of the offsets are IDs (from 0 to n), so ID to word is a simple lookup. Given that the strings are sorted (which they are in termlex), you can then do a reverse-lookup using binary search.

So implementing that transformation shouldn't be difficult.

If I have some time this weekend, I might give it a look in our CIFF Rust code.

**Comment by seanmacavaney** [comment]
Oh, great! Thanks for the pointer. I think it's easy enough to add this directly in `pyterrier_pisa` then, so if you prefer to leave it out of ciff/pyciff, that's fine by me.

**Comment by elshize** [comment]
I think it might be good to include in our ciff project, but can't promise any specific timeline.

One thing I want to note is that off the top of my head, I don't remember if ciff converter will correctly sort the terms. If it doesn't, I'm thinking it should and it should be fixed but be aware of that (I can't verify the behavior right now, so warning just in case).

**Comment by seanmacavaney** [comment]
While you're at it-- would be nice to build the doclex file too.

I wrote the integration such that it will work whether or not the `termlex` or `doclex` files are available -- if they are, it'll use them. If not, it'll create them from `.terms` or `.documents`, respectively.

**Comment by elshize** [comment]
@seanmacavaney just FYI, I opened two PRs here: https://github.com/pisa-engine/ciff/pulls here's my Rust implementation of the lexicon format I described above: https://github.com/pisa-engine/ciff/pull/31/files there are some comment docs there with examples, so it might be helpful as a reference.

There's very little actual work left in order for us to produce these files, but it first must go through code review, and once done, we'll need to release a new version of the base rust package, and only then can we work on including it in the python package. So again, no promises as to when it will be ready, but hopefully soon enough.

As a side note, we are aware that there are quite a few of these paper cuts in PISA, mostly because we always focused on what could further our research as opposed to user experience. However, we would love the project to be useful for as many people as possible. We might not have a lot of free time nowadays to work on it, but I'd personally would be very interested in any things that can be improved, especially if something's very confusing from a user perspective. Worst case, we won't be able to help, but we might just have some spare time here and there to improve user experience a bit.

I'm working on some designs that could help organize different files, add some meta data, and make it easier to run all the commands. That said, it might be some time before any of it is implemented.

**Comment by JMMackenzie** [comment]
Hey @seanmacavaney,

@elshize and I have just finished this release at https://pypi.org/project/pyciff/ so you can now handle the lexicon building within the `ciff_to_pisa` operation. The documentation on the PyPi/Git repo should explain, but essentially you just need to pass an additional Boolean which will trigger the lexicon builds if set to true:

```
pyciff.ciff_to_pisa(input_file, output, generate_lexicons)
```

Note that it will use the `.documents` and `.terms` files generated from the CIFF and build out a `.doclex` and `.termlex` respectively, so you can do away with the explicit lexicon build calls on your side if/when convenient.

Cheers!

**Comment by seanmacavaney** [comment]
Awesome, thanks!
