### ISSUE TITLE
Pisa index for query Re-writing 

### ISSUE THREAD

**Issue by Mandeep-Rathee** [terrierteam/pyterrier_pisa#29]
hey,

I am using a pisa index for ms-marco passage dataset. I want to use it for query rewriting. I am using `pyterrier-pisa==0.0.6` Below is the code for it. 

```python
import pyterrier as pt
pt.init()
from pyterrier_pisa import PisaIndex

index  = PisaIndex.from_dataset('msmarco_passage')
bm25 = PisaIndex.from_dataset('msmarco_passage').bm25()

rm3_pipe = bm25 >> pt.rewrite.RM3(index) >> bm25
pt.Experiment([bm25, rm3_pipe],
            dataset.get_topics(),
            dataset.get_qrels(),
            ["map"]
            )
``` 

I am not able to a Pisa index here. Can you please help me?

Thank in Advance

**Comment by seanmacavaney** [comment]
Oh, so PISA doesn't support rewriting at this time, sorry. RM3 works with a Terrier index, though.
