### ISSUE TITLE
How to index with term weights produced by neural models (e.g., uniCOIL, Splade)?

### ISSUE THREAD

**Issue by thongnt99** [terrierteam/pyterrier_pisa#7]
Hi,
Thanks a lot for this very useful work. 
I wonder if there is anyway to index collections with pre-computed term weights (similar to [this](https://github.com/castorini/pyserini/blob/master/docs/experiments-unicoil.md) in `pyserini`)?

**Comment by cmacdonald** [comment]
For DeepCT, we expanded the terms with their quantised weights - see in particular
https://github.com/terrierteam/pyterrier_deepct/blob/main/pyterrier_deepct/__init__.py#L34

Would definitely be of interest having some uniCOIL indexing pipelines.

Craig
